pipeline{
    agent{
        docker {
            image 'abhishekf5/maven-abhishek-docker-agent:v1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages{
        stage('checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/ARUP-G/Java-CICD-Implementation'
                sh 'echo passed'
            }    
        }
        stage('Build and Test'){
            steps{
                sh 'ls -ltr'
                // build project and JAR file
                sh 'cd spring-boot-app && mvn clean package'
            }
        }
        stage('Build and push Dokcer image'){
            environment {
                DOCKER_IMAGE = "ard3dk/java-cicd:${BUILD_NUMBER}"
                REGISTRY_CREDENTIALS = credentials('docker-cred')
            }
            steps{
                script{
                    sh 'cd spring-boot-app && docker build -t ${DOCKER_IMAGE} .'
                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                    docker.withRegistry('https://index.docker.io/v1/', "docker-cred"){
                        dockerImage.push()
                    }
                }
            }
        }
    }
}